services:
  fastify-app:
    container_name: fastify
    image: fastify_app
    build: ./fastify
    ports:
      - "3000:3000"
    volumes:
      - ./fastify:/app # local project folder into container
      - /app/node_modules # prevent overwriting node_modules
    working_dir: /app
    command: npm run dev # run with hot reload
